### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by devenbhooshan** [aman-iitj/CodeTable#1]
-  You folder **ace-builds** in  https://github.com/aman-iitj/CodeTable/tree/master/CodeTable_app/static is empty but your application required many scripts like **src-noconflict/ace.js , ace.js** 
- Also add  **dj_static** into requirements.txt file. 
-  Also remove unnecessary print statements from views.py

**Comment by aman1k4** [comment]
Thanks @devenbhooshan for the ticket. Issue #1 fixed.
